#Playbook for online store

---

-
  name: 'Push local project to "https://github.com/DanDorado/AnsibleTestWebApp.git"'
  hosts: localhost
  tasks:
    - name: 'git add all'
      command: chdir=/mnt/c/Users/dan.joyce/proto/ans/AWS_Ansible/TestPlayBook git add .

    - name: 'git diff'
      command: chdir=/mnt/c/Users/dan.joyce/proto/ans/AWS_Ansible/TestPlayBook git diff
      register: result

    - name: 'git commit if there is a difference'
      command: chdir=/mnt/c/Users/dan.joyce/proto/ans/AWS_Ansible/TestPlayBook git commit -m 'This commit was made through ansible gitpushpull.yml'
      when: result.stdout == ""

    - name: 'git push'
      command: chdir=/mnt/c/Users/dan.joyce/proto/ans/AWS_Ansible/TestPlayBook git push origin2 master

-
  name: 'Pull project onto controller'
  hosts: controller
  tasks:
    - name: 'initialise git if not already'
      command: chdir=/home/controller/proto git init
    - name: 'pull project'
      command: chdir=/home/controller/proto git pull https://github.com/DanDorado/AnsibleTestWebApp.git
