#Playbook for online store

---

-
  name: 'Set up Git to pull repo from localhost onto controller'
  hosts: controller
  tasks:
    
    - name: 'Initialise'
      debug:
        msg: 'Logging into {{ ansible_host  }} with {{  ansible_user  }}'

    - name: 'Install Git'
      yum:
        name: git
        state: present
      become: true
      become_method: sudo

    - name: 'Check Install'
      command: git --version
      register: result

    - name: debug
      debug:
        var: result

-
  name: 'Install Ansible'
  hosts: controller
  tasks:

    - name: 'Ansible-Install dependencies'
      yum:
        name: epel-release
        state: present
      become: true
      become_method: sudo

    - name: 'Install Ansible'
      yum:
        name: ansible
        state: present
      become: true
      become_method: sudo

    - name: 'Check Install'
      command: ansible --version
      register: result

    - name: debug
      debug:
        var: result

    - name: 'Modify ansible.cfg to allow host_key_checking'
      lineinfile:
        path: /etc/ansible/ansible.cfg
        line: "host_key_checking = FALSE"
        state: present
      become: true
      become_method: sudo


#modify etc/ansible/ansible.cfg with sudo vi, - #   (#host_key_checking)
    
